# Generated by Django 5.2.1 on 2025-05-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
