# Generated by Django 5.2.1 on 2025-05-18 07:18

from django.db import migrations, models

from core.models import CURRENCY_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=CURRENCY_CHOICES,
                default="USD",
                max_length=3,
            ),
        ),
    ]
