# Generated by Django 5.2.1 on 2025-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("auto_income", "Auto Income"),
                    ("auto_expense", "Auto Expense"),
                ],
                max_length=12,
            ),
        ),
    ]
