# Generated by Django 5.2.1 on 2025-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receipt_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
